### ISSUE TITLE
Per-user upload quota for Media Library Upload Field

### ISSUE THREAD

**Issue by Piedone** [Lombiq/Lombiq-Fields#1]
Suggestion by @bleroy: ability to specify (by admins) a max quota (in KB/MB probably) per users on how much they can upload.

While this is useful for the backend too maybe we'd need to examine first how the field works together with Dynamic Forms?

**Comment by BenedekFarkas** [comment]
This was implemented in 2016, but only partially compared to what's described above. A single field can override its destination folder, in which case the field-specific limit applies to all files uploaded for that field regardless of the user. Without such override the files will be placed in a user-specific subfolder and then the limit will be applied per-user. So, there's no overall user quota, only field-specific (which can also be user-specific as well). Since we're not actively developing this module anymore, we're closing the issue.
